### ISSUE TITLE
Doplnit instrukce pro cizince přijíždějící do ČR a Čechy jedoucí za hranice

### ISSUE THREAD

**Issue by brozkeff** [covid19cz/erouska-homepage#137]
Doplnit do FAQ něco na způsob rakouské Stopp-Corona:

"Pocházím ze zahraničí a už jednu contact-tracing aplikaci mám. Jak budu postupovat? 

Contact-tracing aplikací lze mít nainstalováno paralelně více, pouze jedna ale může být aktivována. Během pobytu v Rakousku by to měla být aplikace Stopp-Corona. Velmi důležité: po příjezdu domů by aplikace neměla být hned odinstalována, nýbrž pouze deaktivována! Poté totiž budete nadále obdržovat upozornění, pokud by aplikace zaznamenala kontaktní riziko." 

https://www.austria.info/cz/servis-fakta/bezpecne-do-rakouska/aplikace-stopp-corona

**Comment by vitkolos** [comment]
https://erouska.cz/caste-dotazy#vice-aplikaci
